project_id = "onzfhdrrnbkldwsaqecq"

[functions.ai-interview]
verify_jwt = true

[functions.did-avatar]
verify_jwt = true

[functions.parse-resume]
verify_jwt = true

[functions.send-course-completion-email]
verify_jwt = false
